/*
 * @Author: jianghao
 * @Date: 2022-07-29 09:48:24
 * @LastEditors: jianghao
 * @LastEditTime: 2022-10-17 11:19:55
 */
package app

type RouterGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	CommentRouter
	TagRouter
	ArticltRouter
	BaseMessageRouter
	TaskRouter
	UserRouter
	// Code generated by server End; DO NOT EDIT.
}
