/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Comments: typeof import("./src/components/comments/index.vue")["default"];
    Emoji: typeof import("./src/components/emoji/index.vue")["default"];
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"];
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"];
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"];
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"];
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"];
    NAvatar: typeof import("naive-ui")["NAvatar"];
    NButton: typeof import("naive-ui")["NButton"];
    NCard: typeof import("naive-ui")["NCard"];
    NCarousel: typeof import("naive-ui")["NCarousel"];
    NCarouselItem: typeof import("naive-ui")["NCarouselItem"];
    NConfigProvider: typeof import("naive-ui")["NConfigProvider"];
    NDivider: typeof import("naive-ui")["NDivider"];
    NDrawer: typeof import("naive-ui")["NDrawer"];
    NDrawerContent: typeof import("naive-ui")["NDrawerContent"];
    NDropdown: typeof import("naive-ui")["NDropdown"];
    NEmpty: typeof import("naive-ui")["NEmpty"];
    NForm: typeof import("naive-ui")["NForm"];
    NFormItem: typeof import("naive-ui")["NFormItem"];
    NInput: typeof import("naive-ui")["NInput"];
    NLayout: typeof import("naive-ui")["NLayout"];
    NLayoutContent: typeof import("naive-ui")["NLayoutContent"];
    NLayoutFooter: typeof import("naive-ui")["NLayoutFooter"];
    NLayoutHeader: typeof import("naive-ui")["NLayoutHeader"];
    NList: typeof import("naive-ui")["NList"];
    NListItem: typeof import("naive-ui")["NListItem"];
    NLoadingBarProvider: typeof import("naive-ui")["NLoadingBarProvider"];
    NMessageProvider: typeof import("naive-ui")["NMessageProvider"];
    NNotificationProvider: typeof import("naive-ui")["NNotificationProvider"];
    NPopconfirm: typeof import("naive-ui")["NPopconfirm"];
    NPopover: typeof import("naive-ui")["NPopover"];
    NSpace: typeof import("naive-ui")["NSpace"];
    NSpin: typeof import("naive-ui")["NSpin"];
    NSwitch: typeof import("naive-ui")["NSwitch"];
    NTabPane: typeof import("naive-ui")["NTabPane"];
    NTabs: typeof import("naive-ui")["NTabs"];
    NTag: typeof import("naive-ui")["NTag"];
    NThing: typeof import("naive-ui")["NThing"];
    NUpload: typeof import("naive-ui")["NUpload"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
