package app

type ApiGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	CommentApi
	TagApi
	ArticleApi
	BaseMessageApi
	FileUploadAndDownloadApi
	TaskNameApi
	UserApi
	// Code generated by server End; DO NOT EDIT.
}
