package frontend

import "server/service"

var frontendService = service.ServiceGroupApp.FrontendServiceGroup

type ApiGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	FrontendTagApi
	FrontendArticleApi
	CommentApi
	FrontendUser
	// Code generated by server End; DO NOT EDIT.
}
