package frontend

import (
	"server-fiber/service"

	"github.com/mojocn/base64Captcha"
)

var frontendService = service.ServiceGroupApp.FrontendServiceGroup

type ApiGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	FrontendTagApi
	FrontendArticleApi
	CommentApi
	FrontendUser
	// Code generated by server End; DO NOT EDIT.
}

var store = base64Captcha.DefaultMemStore
var userService = service.ServiceGroupApp.SystemServiceGroup.UserService
var jwtService = service.ServiceGroupApp.SystemServiceGroup.JwtService
