/*
 * @Author: jianghao
 * @Date: 2022-07-29 09:48:24
 * @LastEditors: jianghao
 * @LastEditTime: 2022-10-17 16:54:36
 */
package app

type ServiceGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	CommentService
	TagService
	ArticleService
	BaseMessageService
	FileUploadService
	UserService
	// Code generated by server End; DO NOT EDIT.
}
