package app

type ServiceGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	CommentService
	AppTabService
	ArticleService
	BaseMessageService
	// Code generated by server End; DO NOT EDIT.
}
