package mobile

type ServiceGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	MobileUserService
	MobileLoginService
	MobileRegisterService
	// Code generated by server End; DO NOT EDIT.
}
