package mobile

import "server-fiber/service"

type ApiGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	MobileUserApi
	MobileLoginApi
	RegisterMobile
	// Code generated by server End; DO NOT EDIT.
}

var mobileService = service.ServiceGroupApp.MobileServiceGroup.MobileLoginService
var mobileRegisterService = service.ServiceGroupApp.MobileServiceGroup.MobileRegisterService
